
chip_number: 10
workplace_width_amount: 5

#  For example below:
#  chip_number            = 11 
#  workplace_width_amount = 4

#################################
#       #       #       #       #
#   1   #   2   #   3   #   4   #
#       #       #       #       #
#################################
#       #       #       #       #
#   5   #   6   #   7   #   8   #
#       #       #       #       #
#################################
#       #       #       #       #
#   9   #   10  #   11  #       #
#       #       #       #       #
#################################

#! -------------------------------------------------- !#

# you can choose 2 options: 'scada' or 'human'
use_case: 'human'
